name: pollen_tracker
description: "Sirius: Pollen Tracker."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.3.1 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  # Firebase
  firebase_core: ^2.27.1

  # Logger
  logger: ^2.1.0

  # State-manager
  flutter_bloc: ^8.1.4

  # Routing
  go_router: ^13.2.1

  # Local-storage
  isar: ^3.1.0+1

  # Networking
  dio: ^5.4.1

  # Serialization
  freezed_annotation: ^2.4.1
  json_annotation: ^4.8.1
  flutter_localizations:
    sdk: flutter
  intl: any
  get_it: ^7.6.7
  firebase_crashlytics: ^3.4.19

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

  # Building
  build_runner: ^2.4.8
  freezed: ^2.4.7
  json_serializable: ^6.7.1

flutter:
  uses-material-design: true
  generate: true 
