name: Flutter PR

on:
  push:
    branches:
    - main
    - develop
  pull_request:
    branches:
    - main
    - develop

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      # - run: npm ci && npm run build

      # - uses: actions/setup-java@v2
      #   with:
      #     java-version: '12'
      - uses: subosito/flutter-action@v1
        with:
          flutter-version: '3.19.3'
          channel: 'stable'
      
      - name: Decode google-services.json
        env: 
            GOOGLE_SERVICES_JSON: ${{ secrets.GOOGLE_SERVICES_JSON }}
        run: echo "$GOOGLE_SERVICES_JSON" > android/app/google-services.json
      - name: Decode firebase_option
        env:
          firebase_options_dart: ${{secrets.FIREBASE_OPTION}}
        run : echo "$firebase_options_dart" > lib/firebase_options.dart


      - name: Get dependencies
        run: flutter pub get
        
      - name: Analyze code
        run: flutter analyze

      - name: Format code
        run: dart format --line-length 120 --set-exit-if-changed .
      - name: Stop workflow if previous step failed
        if: failure()
        run: exit 1


      # - uses: actions/upload-artifact@v1
      #   with:
      #     name: release-apk
      #     path: build/app/outputs/apk/release/app-release.apk
      # - name: upload artifact to Firebase App Distribution
      #   uses: wzieba/Firebase-Distribution-Github-Action@v1
      #   with:
      #       appId: ${{secrets.APPID_ANDROID}}
      #       token: ${{secrets.TOKEN}}
      #       groups: pre-tester
      #       file: build/app/outputs/apk/release/app-release.apk